### ISSUE TITLE
[BUG] Blocklist roles in general settings are not coloured like for categories

### ISSUE THREAD

**Issue by eartharoid** [discord-tickets/settings#4]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

Colour

### Environment

```markdown
- OS:
- Node:
- NPM:
- Bot: 4.0.0
```

**Comment by RooRay** [comment]
earth adding the "good first issue" label to this issue:

![obama giving himself a medal](https://github.com/discord-tickets/portal/assets/86845749/cad1650d-2f08-403a-a8a9-26c1588b01fb)

**Comment by eartharoid** [comment]
That's not what it means 🤣

**Comment by RooRay** [comment]
> That's not what it means 🤣

what is it *meant* to mean?

**Comment by eartharoid** [comment]
It's a good (easy) issue for anyone looking to make their first contribution to the project.
You basically just need to copy and paste some code from one page to another.

**Comment by RooRay** [comment]
petition to rename it to "pls fix 4 me"
